on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build_Code:
    runs-on: ubuntu-latest
    environment: AWS Production
    steps:

    #1. First step is to checkout the code.
    #   The code is downloaded from the Github repository to the build server
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main

    #2. Download and install nodeJs in the build server. 
    #   This is required to build the Angular app.
    - name: Setup NodeJs 
      uses: actions/setup-node@v3
      with:
        node-version: '18.19.1'

    # 3. Install the Angular cli and build the code
    #    This compiles publishes the code that can then be deployed.
    - name: Build Angular Application
      run: |
        ls
        npm install -g @angular/cli@16.1.4
        npm install
        ng build --configuration production

  #4. Upload the output Artifact to the Github artifact repository
  #   This will be used in the next job to deploy it to S3
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-portal-artifact
        path: ./dist/
        retention-days: 7
        overwrite: true
        
  #5. Copy the artifact to EC2 instance.
    - name: Deploy to my EC2 instance
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
        SOURCE: "./dist/"
        REMOTE_HOST: "ec2-98-84-226-75.compute-1.amazonaws.com"
        REMOTE_USER: "ubuntu"
        TARGET: "/home/ubuntu/html/angular-demo/"
        #TARGET: "/var/www/html/angular-demo/"
