on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    # Define the type of server required
    runs-on: ubuntu-latest
    environment: AWS Production
    name: Portal - Deploy
    needs: Build_Code
    steps:
      #1. Copy the artifact to EC2 instance.
      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
          SOURCE: "./dist/"
          REMOTE_HOST: "ec2-98-84-226-75.compute-1.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/var/www/html/angular-demo/"
